project:
  type: website
  output-dir: docs

website:
  title: "Bean Lab"
  navbar:
    left:
      - href: people.qmd
        text: People
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: opportunities.qmd
        text: Prospective Students
      - href: publications.qmd
        text: Publications
    tools:
      - icon: github
        href: https://github.com/calpoly-bean-lab
      - icon: instagram
        href: https://www.instagram.com/spatialecologylab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

