---
title: "Teaching"
format: html
---

#### BIO 327: Wildlife Ecology

*Term Typically Offered: SP* \
Principles of ecology as applied to the study of wild vertebrates and their habitats. Emphasis on techniques for collecting and analyzing field data and how these data apply to the study and management of wildlife. Use of the literature, inventory of plants and animal populations, use of maps and databases, quantifying diet and habitat use, determining sex and age and nutritional condition, capture and marking techniques, non-invasive sampling methods.

#### BIO 427: Wildlife Management

*Term Typically Offered: F* \
Important habitats, such as riparian, wetlands, and habitat features important to wildlife, such as vegetation types and snags. Basic concepts of wildlife management. Emphasis on planning and designing habitats to meet the needs of wildlife.

#### BIO 447: Spatial Ecology

*Term Typically Offered: W* \
Effect of geographical space on distribution and abundance of organisms. Analysis of movement, home ranges, connectivity, range limits, and factors that shape these processes. Survey of available tools and data to answer questions in the discipline.
